### PR TITLE
Apologies and version 0.51

### PR DESCRIPTION
**Pull request by slashk**
Apologies for the last pull request. I made the request without pushing my current local repo to github (which is why retrieve_apikey doesn't return the apikey :( ).

Here is the correct version:
- retrieve_token and retrieve_apikey return dictionaries of full prowl server response
- updated example script
- bumped version to 0.51

Sorry again.

### CODE REVIEW

**Comment by jacobb** [comment]
No problem! Let me review this sometime later tonight or tomorrow evening and I'll get it in there.

Also hoping to add a bunch of stuff of my own thinking that my life isn't crazy busy.

**Comment by slashk** [comment]
hey guys, any chance of pulling this in ? it fixes several things from the last pull :)

**Comment by jacobb** [comment]
i can look at this during the pycon sprints--i'm on 3 hour average sleep, so
once i take a nap it'll be the first thing i sprint on (review + commit if
it looks good)

Thanks for the follow up!

**Comment by jacobb** [comment]
checked in + closed

**Pull request merged**
